# Generated by Django 5.1.8 on 2025-04-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='group',
            new_name='group_assigned',
        ),
    ]
